# Example configuration file for rest-template
Server:
  Port: 8000
  LogLevel: debug
DB:
  Host: localhost
  Port: 5432
Auth:
  Secret: secret
  AccessTokenTTL: 86400
  RefreshTokenTTL: 86400
  RateLimit: 1000
